# Dependabot configuration for updates on main, v2, and v3 branches
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Updates for main branch
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 3
    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"

  # Updates for v3 branch
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "v3"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 3
    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"

  # Updates for v2 branch
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "v2"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 3
    groups:
      dev-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"

  # GitHub Actions updates for main branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 3
